// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University_Grant_Application_System.Data;

#nullable disable

namespace University_Grant_Application_System.Migrations
{
    [DbContext(typeof(University_Grant_Application_SystemContext))]
    [Migration("20260211073025_updatedFiletable")]
    partial class updatedFiletable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("University_Grant_Application_System.Models.College", b =>
                {
                    b.Property<int>("CollegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollegeId"));

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CollegeId");

                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.EquipmentExpense", b =>
                {
                    b.Property<int>("EquipmentExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentExpenseId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("EquipmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormTableId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentExpenseId");

                    b.HasIndex("FormTableId");

                    b.ToTable("EquipmentExpenses");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.FormTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("DisseminationBudget")
                        .HasColumnType("real");

                    b.Property<string>("GrantPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("OtherFunding1Amount")
                        .HasColumnType("real");

                    b.Property<string>("OtherFunding1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("OtherFunding2Amount")
                        .HasColumnType("real");

                    b.Property<string>("OtherFunding2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("OtherFunding3Amount")
                        .HasColumnType("real");

                    b.Property<string>("OtherFunding3Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("OtherFunding4Amount")
                        .HasColumnType("real");

                    b.Property<string>("OtherFunding4Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrincipalInvestigatorID")
                        .HasColumnType("int");

                    b.Property<string>("Procedure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timeline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("TotalBudget")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("approvedByDeptChair")
                        .HasColumnType("bit");

                    b.Property<bool?>("isIRB")
                        .HasColumnType("bit");

                    b.Property<string>("pastBudgets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("pastFunding")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FormTable");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.OtherExpense", b =>
                {
                    b.Property<int>("OtherExpensesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtherExpensesId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("FormTableId")
                        .HasColumnType("int");

                    b.Property<string>("OtherExpenseName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OtherExpensesId");

                    b.HasIndex("FormTableId");

                    b.ToTable("OtherExpenses");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.PersonnelExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormTableId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TaxedAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("FormTableId");

                    b.ToTable("PersonnelExpenses");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("FormTableId")
                        .HasColumnType("int");

                    b.Property<bool>("ReviewDone")
                        .HasColumnType("bit");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("totalScore")
                        .HasColumnType("float");

                    b.HasKey("ReviewId");

                    b.HasIndex("FormTableId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.School", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolId"));

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolId");

                    b.HasIndex("CollegeId");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.TravelExpense", b =>
                {
                    b.Property<int>("TravelExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TravelExpenseId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("FormTableId")
                        .HasColumnType("int");

                    b.Property<string>("TravelName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TravelExpenseId");

                    b.HasIndex("FormTableId");

                    b.ToTable("TravelExpenses");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.UploadedFile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("FormTableId")
                        .HasColumnType("int");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("FormTableId");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("committeeMemberStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("userType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("CollegeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.Department", b =>
                {
                    b.HasOne("University_Grant_Application_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.EquipmentExpense", b =>
                {
                    b.HasOne("University_Grant_Application_System.Models.FormTable", "FormTable")
                        .WithMany("EquipmentExpenses")
                        .HasForeignKey("FormTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTable");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.FormTable", b =>
                {
                    b.HasOne("University_Grant_Application_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.OtherExpense", b =>
                {
                    b.HasOne("University_Grant_Application_System.Models.FormTable", "FormTable")
                        .WithMany("OtherExpenses")
                        .HasForeignKey("FormTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTable");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.PersonnelExpense", b =>
                {
                    b.HasOne("University_Grant_Application_System.Models.FormTable", "FormTable")
                        .WithMany("PersonnelExpenses")
                        .HasForeignKey("FormTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTable");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.Review", b =>
                {
                    b.HasOne("University_Grant_Application_System.Models.FormTable", "FormTable")
                        .WithMany("Reviews")
                        .HasForeignKey("FormTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Grant_Application_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("FormTable");

                    b.Navigation("User");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.School", b =>
                {
                    b.HasOne("University_Grant_Application_System.Models.College", "College")
                        .WithMany()
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.TravelExpense", b =>
                {
                    b.HasOne("University_Grant_Application_System.Models.FormTable", "FormTable")
                        .WithMany("TravelExpenses")
                        .HasForeignKey("FormTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTable");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.UploadedFile", b =>
                {
                    b.HasOne("University_Grant_Application_System.Models.FormTable", "FormTable")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("FormTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTable");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.User", b =>
                {
                    b.HasOne("University_Grant_Application_System.Models.College", "College")
                        .WithMany()
                        .HasForeignKey("CollegeId");

                    b.HasOne("University_Grant_Application_System.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("University_Grant_Application_System.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId");

                    b.Navigation("College");

                    b.Navigation("Department");

                    b.Navigation("School");
                });

            modelBuilder.Entity("University_Grant_Application_System.Models.FormTable", b =>
                {
                    b.Navigation("EquipmentExpenses");

                    b.Navigation("OtherExpenses");

                    b.Navigation("PersonnelExpenses");

                    b.Navigation("Reviews");

                    b.Navigation("TravelExpenses");

                    b.Navigation("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
